#include <driver/spi_master.h>

#define LORA_SPI_HOST (SPI2_HOST)
#define LCD_SPI_HOST (SPI3_HOST)

#define LCD_GPIO_SCLK (GPIO_NUM_36)
#define LCD_GPIO_MOSI (GPIO_NUM_35)
#define LCD_GPIO_RST (GPIO_NUM_47)
#define LCD_GPIO_DC (GPIO_NUM_40)
#define LCD_GPIO_CS (GPIO_NUM_39)
#define LCD_GPIO_BL (GPIO_NUM_21)

#define LORA_GPIO_MISO (GPIO_NUM_13)
#define LORA_GPIO_MOSI (GPIO_NUM_11)
#define LORA_GPIO_SCLK (GPIO_NUM_12)
#define LORA_GPIO_NSS (GPIO_NUM_10)
#define LORA_GPIO_RST (GPIO_NUM_7)
#define LORA_GPIO_BUSY (GPIO_NUM_9)
#define LORA_GPIO_TXEN (GPIO_NUM_4)
#define LORA_GPIO_RXEN (GPIO_NUM_5)
#define LORA_GPIO_DIO1 (GPIO_NUM_6)

#define BUTTON_GLOW_GPIO_TYPE_FAULT (GPIO_NUM_37)
#define BUTTON_GLOW_GPIO_TYPE_REFUSAL (GPIO_NUM_48)
#define BUTTON_GLOW_GPIO_TYPE_DIS (GPIO_NUM_45)
#define BUTTON_GLOW_GPIO_TYPE_RESET (GPIO_NUM_41)
#define BUTTON_GLOW_GPIO_TYPE_ACTIVATE (GPIO_NUM_46)

#define BUTTON_INPUT_GPIO_TYPE_FAULT (GPIO_NUM_16)
#define BUTTON_INPUT_GPIO_TYPE_REFUSAL (GPIO_NUM_8)
#define BUTTON_INPUT_GPIO_TYPE_DIS (GPIO_NUM_18)
#define BUTTON_INPUT_GPIO_TYPE_RESET (GPIO_NUM_17)
#define BUTTON_INPUT_GPIO_TYPE_ACTIVATE (GPIO_NUM_15)

#define RTC_SCL (GPIO_NUM_1)
#define RTC_SDA (GPIO_NUM_2)
#define RTC_SQW (GPIO_NUM_20)

#define BUZZER_GPIO (GPIO_NUM_42)