services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: drinklist
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080