#include <driver/spi_master.h>

#define LORA_SPI_HOST (SPI2_HOST)
#define LCD_SPI_HOST (SPI3_HOST)

#define LCD_GPIO_SCLK (GPIO_NUM_36)
#define LCD_GPIO_MOSI (GPIO_NUM_35)
#define LCD_GPIO_RST (GPIO_NUM_38)
#define LCD_GPIO_DC (GPIO_NUM_40)
#define LCD_GPIO_CS (GPIO_NUM_39)
#define LCD_GPIO_BL (GPIO_NUM_21)

#define BUTTON_GLOW_GPIO_TYPE_FAULT (GPIO_NUM_37)
#define BUTTON_GLOW_GPIO_TYPE_REFUSAL (GPIO_NUM_48)
#define BUTTON_GLOW_GPIO_TYPE_DIS (GPIO_NUM_45)
#define BUTTON_GLOW_GPIO_TYPE_RESET (GPIO_NUM_41)
#define BUTTON_GLOW_GPIO_TYPE_ACTIVATE (GPIO_NUM_46)

#define BUTTON_INPUT_GPIO_TYPE_FAULT (GPIO_NUM_16)
#define BUTTON_INPUT_GPIO_TYPE_REFUSAL (GPIO_NUM_8)
#define BUTTON_INPUT_GPIO_TYPE_DIS (GPIO_NUM_18)
#define BUTTON_INPUT_GPIO_TYPE_RESET (GPIO_NUM_17)
#define BUTTON_INPUT_GPIO_TYPE_ACTIVATE (GPIO_NUM_15)

#define RTC_SCL (GPIO_NUM_1)
#define RTC_SDA (GPIO_NUM_2)
#define RTC_SQW (GPIO_NUM_3)

#define BUZZER_GPIO (GPIO_NUM_42)
#define TRIGGER_PIN_1 (GPIO_NUM_47)
#define TRIGGER_PIN_2 (GPIO_NUM_44)