#define BUZZER_STARTUP 1
#define BUZZER_TRIGGER 2
#define BUZZER_INDICATE_ERROR 3
#define BUZZER_7_MINUTE_TIMER_START 4
#define BUZZER_7_MINUTE_TIMER_END 5
#define BUZZER_BUTTON_PRESS 6

void Buzzer_Task(void *params);
