# This is a basic workflow to help you get started with Actions

name: Build Project flooding

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    if: "github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'build_and_push')" # Skip if 'build_and_push' label not exists
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3.1
          target: esp32s3
          path: "measure-stations"
          command: idf.py build
      - name: Archive build output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            measure-stations/build/measure-stations.bin