name: Build projects and upload binaries

on:
  push:
    branches: ["master"]
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
  workflow_dispatch:

jobs:
  build-measure-stations-lora:
    if: "github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'build_and_push')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: esp-idf build for measure-stations-lora
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4.1
          target: esp32s3
          path: "measure-stations-lora"
          command: idf.py build
      - name: Upload measure-stations-lora build output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: measure-stations-lora-bin
          path: measure-stations-lora/build/measure-stations-lora.bin

  build-dogdog-controller:
    if: "github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'build_and_push')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: esp-idf build for dogdog-controller
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4.1
          target: esp32s3
          path: "dogdog-controller"
          command: idf.py build
      - name: Upload dogdog-controller build output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dogdog-controller-bin
          path: dogdog-controller/build/dogdog-controller.bin

  release:
    needs: [build-measure-stations-lora, build-dogdog-controller]  # Ensures this job runs after all build jobs complete
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Download measure-stations-lora artifact
        uses: actions/download-artifact@v4
        with:
          name: measure-stations-lora-bin

      - name: Download dogdog-controller artifact
        uses: actions/download-artifact@v4
        with:
          name: dogdog-controller-bin

      - name: Delete previous 'latest' release (if exists)
        continue-on-error: true  # this prevents workflow failure if tag doesn't exist
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create new 'latest' release and upload binary
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: latest
          files: |
            measure-stations-lora.bin
            dogdog-controller.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
