name: Build projects and upload binaries

on:
  push:
    branches: ["master"]
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
  workflow_dispatch:

jobs:
  build-measure-stations:
    if: "github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'build_and_push')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: esp-idf build for measure-stations
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4.1
          target: esp32
          path: "measure-stations"
          command: idf.py build
      - name: Upload measure-stations build output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: measure-stations-bin
          path: measure-stations/build/measure-stations.bin

  build-timepanel:
    if: "github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'build_and_push')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: esp-idf build for timepanel
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4.1
          target: esp32
          path: "timepanel"
          command: idf.py build
      - name: Upload timepanel build output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: timepanel-bin
          path: timepanel/build/timepanel.bin
  build-remote:
    if: "github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'build_and_push')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: esp-idf build for remote
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4.1
          target: esp32
          path: "remote"
          command: idf.py build
      - name: Upload remote build output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: remote-bin
          path: remote/build/remote.bin
  build-remote-pc:
    if: "github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'build_and_push')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: esp-idf build for remote-pc
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4.1
          target: esp32s3
          path: "remote-pc"
          command: idf.py build
      - name: Upload remote-pc build output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: remote-pc-bin
          path: remote-pc/build/remote-pc.bin
  build-timepanel-lcd:
    if: "github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'build_and_push')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: esp-idf build for timepanel-lcd
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4.1
          target: esp32
          path: "timepanel-lcd"
          command: idf.py build
      - name: Upload timepanel-lcd build output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: timepanel-lcd-bin
          path: timepanel-lcd/build/timepanel-lcd.bin
  build-timepanel-clock-lcd:
    if: "github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'build_and_push')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: esp-idf build for timepanel-clock-lcd
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.1.4
          target: esp32s3
          path: "timepanel-clock-lcd"
          command: idf.py build
      - name: Upload timepanel-clock-lcd build output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: timepanel-clock-lcd-bin
          path: timepanel-clock-lcd/build/timepanel-clock-lcd.bin

  release:
    needs: [build-measure-stations, build-timepanel, build-remote, build-remote-pc, build-timepanel-lcd,build-timepanel-clock-lcd]  # Ensures this job runs after both build jobs complete
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Download measure-stations artifact
        uses: actions/download-artifact@v4
        with:
          name: measure-stations-bin

      - name: Download timepanel artifact
        uses: actions/download-artifact@v4
        with:
          name: timepanel-bin

      - name: Download remote artifact
        uses: actions/download-artifact@v4
        with:
          name: remote-bin

      - name: Download remote-pc artifact
        uses: actions/download-artifact@v4
        with:
          name: remote-pc-bin

      - name: Download timepanel-lcd artifact
        uses: actions/download-artifact@v4
        with:
          name: timepanel-lcd-bin
      
      - name: Download timepanel-clock-lcd artifact
        uses: actions/download-artifact@v4
        with:
          name: timepanel-clock-lcd         

      - name: Delete previous 'latest' release (if exists)
        continue-on-error: true  # this prevents workflow failure if tag doesn't exist
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create new 'latest' release and upload binary
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: latest
          files: |
            measure-stations.bin
            timepanel.bin
            remote.bin
            remote-pc.bin
            timepanel-lcd.bin
            timepanel-clock-lcd.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
