name: Build and Overwrite Latest Release

on:
  push:
    branches: [master]  # or any branches you want

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build your binary
        run: |
          mkdir -p dist
          echo "hello from $(date)" > dist/your_binary  # Replace this with real build logic

      - name: Delete previous 'latest' release (if exists)
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new 'latest' release and upload binary
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: latest
          files: dist/your_binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
